CREATE USER user1 IDENTIFIED BY 'user1';
GRANT SELECT ON ksiegarnia1.* TO user1;

CREATE USER user2 IDENTIFIED BY 'user2';
GRANT SELECT, INSERT, UPDATE, DELETE ON ksiegarnia1.* TO user2;

FLUSH PRIVILEGES;
